add unit test framework via Check

diff --git a/trunk/test/check/Makefile.in b/trunk/test/check/Makefile.in
--- a/trunk/test/check/Makefile.in
+++ b/trunk/test/check/Makefile.in
@@ -72,39 +72,69 @@ AUTOMAKE_OPTIONS = foreign no-dependencies
 
 DISTCLEANFILES = *~
 
-sbin_PROGRAMS = dnet
+INCLUDES = @CHECKINC@
 
-dnet_SOURCES = addr.c arp.c aton.c aton.h dnet.c eth.c fw.c hex.c 	icmp.c intf.c ip.c mod.h rand.c route.c send.c tcp.c udp.c
+TESTS = check_addr check_arp check_eth check_fw check_ip check_intf 	check_rand check_route
 
 
-man_MANS = dnet.8
+noinst_PROGRAMS = $(TESTS)
 
-EXTRA_DIST = $(man_MANS)
+check_addr_SOURCES = check_addr.c
+check_arp_SOURCES = check_arp.c
+check_eth_SOURCES = check_eth.c
+check_fw_SOURCES = check_fw.c
+check_intf_SOURCES = check_intf.c
+check_ip_SOURCES = check_ip.c
+check_rand_SOURCES = check_rand.c
+check_route_SOURCES = check_route.c
 
-LDADD = $(top_srcdir)/src/libdnet.a
+LDADD = $(top_srcdir)/src/libdnet.a @CHECKLIB@
 mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
 CONFIG_HEADER = ../../include/config.h
 CONFIG_CLEAN_FILES = 
-PROGRAMS =  $(sbin_PROGRAMS)
+PROGRAMS =  $(noinst_PROGRAMS)
 
 
 DEFS = @DEFS@ -I. -I$(srcdir) -I../../include
 CPPFLAGS = @CPPFLAGS@
 LDFLAGS = @LDFLAGS@
 LIBS = @LIBS@
-dnet_OBJECTS =  addr.o arp.o aton.o dnet.o eth.o fw.o hex.o icmp.o \
-intf.o ip.o rand.o route.o send.o tcp.o udp.o
-dnet_LDADD = $(LDADD)
-dnet_DEPENDENCIES =  $(top_srcdir)/src/libdnet.a
-dnet_LDFLAGS = 
+check_addr_OBJECTS =  check_addr.o
+check_addr_LDADD = $(LDADD)
+check_addr_DEPENDENCIES =  $(top_srcdir)/src/libdnet.a
+check_addr_LDFLAGS = 
+check_arp_OBJECTS =  check_arp.o
+check_arp_LDADD = $(LDADD)
+check_arp_DEPENDENCIES =  $(top_srcdir)/src/libdnet.a
+check_arp_LDFLAGS = 
+check_eth_OBJECTS =  check_eth.o
+check_eth_LDADD = $(LDADD)
+check_eth_DEPENDENCIES =  $(top_srcdir)/src/libdnet.a
+check_eth_LDFLAGS = 
+check_fw_OBJECTS =  check_fw.o
+check_fw_LDADD = $(LDADD)
+check_fw_DEPENDENCIES =  $(top_srcdir)/src/libdnet.a
+check_fw_LDFLAGS = 
+check_ip_OBJECTS =  check_ip.o
+check_ip_LDADD = $(LDADD)
+check_ip_DEPENDENCIES =  $(top_srcdir)/src/libdnet.a
+check_ip_LDFLAGS = 
+check_intf_OBJECTS =  check_intf.o
+check_intf_LDADD = $(LDADD)
+check_intf_DEPENDENCIES =  $(top_srcdir)/src/libdnet.a
+check_intf_LDFLAGS = 
+check_rand_OBJECTS =  check_rand.o
+check_rand_LDADD = $(LDADD)
+check_rand_DEPENDENCIES =  $(top_srcdir)/src/libdnet.a
+check_rand_LDFLAGS = 
+check_route_OBJECTS =  check_route.o
+check_route_LDADD = $(LDADD)
+check_route_DEPENDENCIES =  $(top_srcdir)/src/libdnet.a
+check_route_LDFLAGS = 
 CFLAGS = @CFLAGS@
 COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
 CCLD = $(CC)
 LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(LDFLAGS) -o $@
-man8dir = $(mandir)/man8
-MANS = $(man_MANS)
-
-NROFF = nroff
 DIST_COMMON =  Makefile.am Makefile.in
 
 
@@ -112,44 +142,28 @@ DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)
 
 TAR = tar
 GZIP_ENV = --best
-SOURCES = $(dnet_SOURCES)
-OBJECTS = $(dnet_OBJECTS)
+SOURCES = $(check_addr_SOURCES) $(check_arp_SOURCES) $(check_eth_SOURCES) $(check_fw_SOURCES) $(check_ip_SOURCES) $(check_intf_SOURCES) $(check_rand_SOURCES) $(check_route_SOURCES)
+OBJECTS = $(check_addr_OBJECTS) $(check_arp_OBJECTS) $(check_eth_OBJECTS) $(check_fw_OBJECTS) $(check_ip_OBJECTS) $(check_intf_OBJECTS) $(check_rand_OBJECTS) $(check_route_OBJECTS)
 
 all: all-redirect
 .SUFFIXES:
 .SUFFIXES: .S .c .o .s
 $(srcdir)/Makefile.in: Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) $(top_srcdir)/Makefile.am.common
-	cd $(top_srcdir) && $(AUTOMAKE) --foreign test/dnet/Makefile
+	cd $(top_srcdir) && $(AUTOMAKE) --foreign test/check/Makefile
 
 Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
 	cd $(top_builddir) \
 	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status
 
 
-mostlyclean-sbinPROGRAMS:
+mostlyclean-noinstPROGRAMS:
 
-clean-sbinPROGRAMS:
-	-test -z "$(sbin_PROGRAMS)" || rm -f $(sbin_PROGRAMS)
+clean-noinstPROGRAMS:
+	-test -z "$(noinst_PROGRAMS)" || rm -f $(noinst_PROGRAMS)
 
-distclean-sbinPROGRAMS:
+distclean-noinstPROGRAMS:
 
-maintainer-clean-sbinPROGRAMS:
-
-install-sbinPROGRAMS: $(sbin_PROGRAMS)
-	@$(NORMAL_INSTALL)
-	$(mkinstalldirs) $(DESTDIR)$(sbindir)
-	@list='$(sbin_PROGRAMS)'; for p in $$list; do \
-	  if test -f $$p; then \
-	    echo "  $(INSTALL_PROGRAM) $$p $(DESTDIR)$(sbindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`"; \
-	     $(INSTALL_PROGRAM) $$p $(DESTDIR)$(sbindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
-	  else :; fi; \
-	done
-
-uninstall-sbinPROGRAMS:
-	@$(NORMAL_UNINSTALL)
-	list='$(sbin_PROGRAMS)'; for p in $$list; do \
-	  rm -f $(DESTDIR)$(sbindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
-	done
+maintainer-clean-noinstPROGRAMS:
 
 .c.o:
 	$(COMPILE) -c $<
@@ -170,48 +184,37 @@ distclean-compile:
 
 maintainer-clean-compile:
 
-dnet: $(dnet_OBJECTS) $(dnet_DEPENDENCIES)
-	@rm -f dnet
-	$(LINK) $(dnet_LDFLAGS) $(dnet_OBJECTS) $(dnet_LDADD) $(LIBS)
+check_addr: $(check_addr_OBJECTS) $(check_addr_DEPENDENCIES)
+	@rm -f check_addr
+	$(LINK) $(check_addr_LDFLAGS) $(check_addr_OBJECTS) $(check_addr_LDADD) $(LIBS)
 
-install-man8:
-	$(mkinstalldirs) $(DESTDIR)$(man8dir)
-	@list='$(man8_MANS)'; \
-	l2='$(man_MANS)'; for i in $$l2; do \
-	  case "$$i" in \
-	    *.8*) list="$$list $$i" ;; \
-	  esac; \
-	done; \
-	for i in $$list; do \
-	  if test -f $(srcdir)/$$i; then file=$(srcdir)/$$i; \
-	  else file=$$i; fi; \
-	  ext=`echo $$i | sed -e 's/^.*\\.//'`; \
-	  inst=`echo $$i | sed -e 's/\\.[0-9a-z]*$$//'`; \
-	  inst=`echo $$inst | sed '$(transform)'`.$$ext; \
-	  echo " $(INSTALL_DATA) $$file $(DESTDIR)$(man8dir)/$$inst"; \
-	  $(INSTALL_DATA) $$file $(DESTDIR)$(man8dir)/$$inst; \
-	done
+check_arp: $(check_arp_OBJECTS) $(check_arp_DEPENDENCIES)
+	@rm -f check_arp
+	$(LINK) $(check_arp_LDFLAGS) $(check_arp_OBJECTS) $(check_arp_LDADD) $(LIBS)
 
-uninstall-man8:
-	@list='$(man8_MANS)'; \
-	l2='$(man_MANS)'; for i in $$l2; do \
-	  case "$$i" in \
-	    *.8*) list="$$list $$i" ;; \
-	  esac; \
-	done; \
-	for i in $$list; do \
-	  ext=`echo $$i | sed -e 's/^.*\\.//'`; \
-	  inst=`echo $$i | sed -e 's/\\.[0-9a-z]*$$//'`; \
-	  inst=`echo $$inst | sed '$(transform)'`.$$ext; \
-	  echo " rm -f $(DESTDIR)$(man8dir)/$$inst"; \
-	  rm -f $(DESTDIR)$(man8dir)/$$inst; \
-	done
-install-man: $(MANS)
-	@$(NORMAL_INSTALL)
-	$(MAKE) $(AM_MAKEFLAGS) install-man8
-uninstall-man:
-	@$(NORMAL_UNINSTALL)
-	$(MAKE) $(AM_MAKEFLAGS) uninstall-man8
+check_eth: $(check_eth_OBJECTS) $(check_eth_DEPENDENCIES)
+	@rm -f check_eth
+	$(LINK) $(check_eth_LDFLAGS) $(check_eth_OBJECTS) $(check_eth_LDADD) $(LIBS)
+
+check_fw: $(check_fw_OBJECTS) $(check_fw_DEPENDENCIES)
+	@rm -f check_fw
+	$(LINK) $(check_fw_LDFLAGS) $(check_fw_OBJECTS) $(check_fw_LDADD) $(LIBS)
+
+check_ip: $(check_ip_OBJECTS) $(check_ip_DEPENDENCIES)
+	@rm -f check_ip
+	$(LINK) $(check_ip_LDFLAGS) $(check_ip_OBJECTS) $(check_ip_LDADD) $(LIBS)
+
+check_intf: $(check_intf_OBJECTS) $(check_intf_DEPENDENCIES)
+	@rm -f check_intf
+	$(LINK) $(check_intf_LDFLAGS) $(check_intf_OBJECTS) $(check_intf_LDADD) $(LIBS)
+
+check_rand: $(check_rand_OBJECTS) $(check_rand_DEPENDENCIES)
+	@rm -f check_rand
+	$(LINK) $(check_rand_LDFLAGS) $(check_rand_OBJECTS) $(check_rand_LDADD) $(LIBS)
+
+check_route: $(check_route_OBJECTS) $(check_route_DEPENDENCIES)
+	@rm -f check_route
+	$(LINK) $(check_route_LDFLAGS) $(check_route_OBJECTS) $(check_route_LDADD) $(LIBS)
 
 tags: TAGS
 
@@ -244,7 +247,7 @@ maintainer-clean-tags:
 
 distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)
 
-subdir = test/dnet
+subdir = test/check
 
 distdir: $(DISTFILES)
 	@for file in $(DISTFILES); do \
@@ -257,31 +260,56 @@ distdir: $(DISTFILES)
 	    || cp -p $$d/$$file $(distdir)/$$file || :; \
 	  fi; \
 	done
+check-TESTS: $(TESTS)
+	@failed=0; all=0; \
+	srcdir=$(srcdir); export srcdir; \
+	for tst in $(TESTS); do \
+	  if test -f $$tst; then dir=.; \
+	  else dir="$(srcdir)"; fi; \
+	  if $(TESTS_ENVIRONMENT) $$dir/$$tst; then \
+	    all=`expr $$all + 1`; \
+	    echo "PASS: $$tst"; \
+	  elif test $$? -ne 77; then \
+	    all=`expr $$all + 1`; \
+	    failed=`expr $$failed + 1`; \
+	    echo "FAIL: $$tst"; \
+	  fi; \
+	done; \
+	if test "$$failed" -eq 0; then \
+	  banner="All $$all tests passed"; \
+	else \
+	  banner="$$failed of $$all tests failed"; \
+	fi; \
+	dashes=`echo "$$banner" | sed s/./=/g`; \
+	echo "$$dashes"; \
+	echo "$$banner"; \
+	echo "$$dashes"; \
+	test "$$failed" -eq 0
 info-am:
 info: info-am
 dvi-am:
 dvi: dvi-am
 check-am: all-am
+	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
 check: check-am
 installcheck-am:
 installcheck: installcheck-am
-install-exec-am: install-sbinPROGRAMS
+install-exec-am:
 install-exec: install-exec-am
 
-install-data-am: install-man
+install-data-am:
 install-data: install-data-am
 
 install-am: all-am
 	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
 install: install-am
-uninstall-am: uninstall-sbinPROGRAMS uninstall-man
+uninstall-am:
 uninstall: uninstall-am
-all-am: Makefile $(PROGRAMS) $(MANS)
+all-am: Makefile $(PROGRAMS)
 all-redirect: all-am
 install-strip:
 	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
 installdirs:
-	$(mkinstalldirs)  $(DESTDIR)$(sbindir) $(DESTDIR)$(mandir)/man8
 
 
 mostlyclean-generic:
@@ -294,22 +322,22 @@ distclean-generic:
 	-test -z "$(DISTCLEANFILES)" || rm -f $(DISTCLEANFILES)
 
 maintainer-clean-generic:
-mostlyclean-am:  mostlyclean-sbinPROGRAMS mostlyclean-compile \
+mostlyclean-am:  mostlyclean-noinstPROGRAMS mostlyclean-compile \
 		mostlyclean-tags mostlyclean-generic
 
 mostlyclean: mostlyclean-am
 
-clean-am:  clean-sbinPROGRAMS clean-compile clean-tags clean-generic \
+clean-am:  clean-noinstPROGRAMS clean-compile clean-tags clean-generic \
 		mostlyclean-am
 
 clean: clean-am
 
-distclean-am:  distclean-sbinPROGRAMS distclean-compile distclean-tags \
+distclean-am:  distclean-noinstPROGRAMS distclean-compile distclean-tags \
 		distclean-generic clean-am
 
 distclean: distclean-am
 
-maintainer-clean-am:  maintainer-clean-sbinPROGRAMS \
+maintainer-clean-am:  maintainer-clean-noinstPROGRAMS \
 		maintainer-clean-compile maintainer-clean-tags \
 		maintainer-clean-generic distclean-am
 	@echo "This command is intended for maintainers to use;"
@@ -317,21 +345,17 @@ maintainer-clean-am:  maintainer-clean-sbinPROGRAMS \
 
 maintainer-clean: maintainer-clean-am
 
-.PHONY: mostlyclean-sbinPROGRAMS distclean-sbinPROGRAMS \
-clean-sbinPROGRAMS maintainer-clean-sbinPROGRAMS uninstall-sbinPROGRAMS \
-install-sbinPROGRAMS mostlyclean-compile distclean-compile \
-clean-compile maintainer-clean-compile install-man8 uninstall-man8 \
-install-man uninstall-man tags mostlyclean-tags distclean-tags \
-clean-tags maintainer-clean-tags distdir info-am info dvi-am dvi check \
-check-am installcheck-am installcheck install-exec-am install-exec \
-install-data-am install-data install-am install uninstall-am uninstall \
-all-redirect all-am all installdirs mostlyclean-generic \
-distclean-generic clean-generic maintainer-clean-generic clean \
-mostlyclean distclean maintainer-clean
+.PHONY: mostlyclean-noinstPROGRAMS distclean-noinstPROGRAMS \
+clean-noinstPROGRAMS maintainer-clean-noinstPROGRAMS \
+mostlyclean-compile distclean-compile clean-compile \
+maintainer-clean-compile tags mostlyclean-tags distclean-tags \
+clean-tags maintainer-clean-tags distdir check-TESTS info-am info \
+dvi-am dvi check check-am installcheck-am installcheck install-exec-am \
+install-exec install-data-am install-data install-am install \
+uninstall-am uninstall all-redirect all-am all installdirs \
+mostlyclean-generic distclean-generic clean-generic \
+maintainer-clean-generic clean mostlyclean distclean maintainer-clean
 
-
-dnet.8.txt: dnet.8
-	groff -t -e -mdoc -Tascii dnet.8 | col -bx > $@
 
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
